site_name: Docs Site

nav:
  - Home: index.md
  - CV:
      - Academic projects:
          - Thesis: cv/academic-projects/academic-projects.md
      - Writing samples:
          - Writing samples: CV/writing-samples/writing-samples.md
theme:
  name: harmonic

plugins:
  - search
  - mike:
      alias_type: copy
  - print-site:
      enabled: !ENV [ENABLE_PDF_EXPORT, false]
      add_cover_page: true
      enumerate_headings: false
      print_page_title: CodeFusion Studio
      cover_page_template: "docs/assets/templates/cover_page.tpl"

