site_name: Caroline Maguire – Technical Writing Portfolio

nav:
  - Home: index.md
  - CV:
      - Overview: cv/index.md
      - Academic projects: cv/academic-projects/academic-projects.md
      - Writing samples: cv/writing-samples/writing-samples.md
  - Projects:
      - Overview: projects/index.md
      - AI Master's project: projects/ai-masters-project/index.md
      - FastAPI microservice: projects/fast-dsp-microservice/deploy.md

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mike:
      alias_type: copy
  - print-site:
      enabled: !ENV [ENABLE_PDF_EXPORT, false]
      add_cover_page: true
      enumerate_headings: false
      print_page_title: Technical Writing Portfolio
      cover_page_template: docs/assets/templates/cover_page.tpl

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - footnotes
  - codehilite
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed


