name: Deploy MkDocs Site

on:
  push:
    branches:
      - main
  workflow_dispatch:  # allows you to run manually from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install MkDocs and Harmonic theme
        run: |
          pip install mkdocs
          pip install git+https://github.com/analogdevicesinc/harmonic-mkdocs-theme.git
          pip install mkdocs-print-site-plugin mike

      - name: Build site
        run: mkdocs build

      - name: Set Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy to GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          mkdocs gh-deploy --force --remote-name origin --remote-branch gh-pages
