name: Generate Eisvogel styled PDF using pandoc and store in GitHub repo

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install TeX Live and Pandoc
        run: |
          sudo apt update
          sudo apt install -y texlive texlive-xetex pandoc wget unzip

      - name: Download Eisvogel template
        run: |
          wget https://raw.githubusercontent.com/Wandmalfarbe/pandoc-latex-template/master/template-multi-file/eisvogel.latex -O eisvogel.latex
          wget https://raw.githubusercontent.com/Wandmalfarbe/pandoc-latex-template/master/template-multi-file/passoptions.latex -O passoptions.latex
          wget https://raw.githubusercontent.com/Wandmalfarbe/pandoc-latex-template/master/template-multi-file/fonts.latex -O fonts.latex
          wget https://raw.githubusercontent.com/Wandmalfarbe/pandoc-latex-template/master/template-multi-file/font-settings.latex -O font-settings.latex

      - name: Generate PDF
        run: |
          pandoc deployment-guide.md \
            -o deployment-guide.pdf \
            --template eisvogel.latex \
            --pdf-engine=xelatex \
            --highlight-style tango

      - name: Commit PDF to repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add deployment-guide.pdf
          git commit -m "Auto-generate PDF from deployment-guide.md" || echo "No changes to commit"
          git push
