name: Build PDF with Pandoc

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install TeX Live and Pandoc
        run: |
          sudo apt update
          sudo apt install -y texlive texlive-xetex pandoc wget unzip

      - name: Download Eisvogel template
        run: |
          wget https://raw.githubusercontent.com/Wandmalfarbe/pandoc-latex-template/master/eisvogel.latex -O eisvogel.latex

      - name: Generate PDF
        run: |
          pandoc deployment-guide.md \
            -o deployment-guide.pdf \
            --template eisvogel.latex \
            --pdf-engine=xelatex \
            --highlight-style tango

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deployment-guide-pdf
          path: deployment-guide.pdf
